name: SwiftBuild

on:
  pull_request:
    paths:
      - '**/*.swift'

jobs:
  build:
    name: Build-PitchPerfect
    runs-on: macos
    strategy:
            matrix:
              destination: ['platform=iOS Simulator,OS=13.2,name=iPhone X']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: xcodebuild clean build -project PitchPerfect/PitchPerfect.xcodeproj -scheme Pitchperfect -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
